[character]
name = Cozzynk
last_updated = 2026-05-06

[skills]
; Spaceship Command
Spaceship Command = 5
Gallente Frigate = 3
Gallente Destroyer = 3
Gallente Cruiser = 1
Gallente Hauler = 1
Caldari Hauler = 1
ORE Hauler = 3
Mining Frigate = 3
Mining Barge = 3
Industrial Command Ships = 2
Industrial Reconfiguration = 1

; Mining
Mining = 5
Mining Upgrades = 4
Astrogeology = 4
Mining Foreman = 5
Mining Director = 1
Mining Drone Operation = 3
Survey = 3

; Industry
Industry = 5
Mass Production = 5
Advanced Mass Production = 1
Reprocessing = 3

; Drones
Drones = 5
Drone Avionics = 3
Drone Navigation = 3
Light Drone Operation = 3
Medium Drone Operation = 1

; Gunnery
Gunnery = 4
Small Hybrid Turret = 3
Medium Hybrid Turret = 3
Controlled Bursts = 2
Motion Prediction = 2
Rapid Firing = 2
Sharpshooter = 2
Trajectory Analysis = 1

; Missiles
Missile Launcher Operation = 1

; Defence
Shield Operation = 3
Shield Management = 2
Shield Upgrades = 1
Tactical Shield Manipulation = 1
Hull Upgrades = 4
Mechanics = 3
Repair Systems = 3

; Engineering / fitting
CPU Management = 4
Power Grid Management = 4
Capacitor Management = 3
Capacitor Systems Operation = 3
Energy Grid Upgrades = 1
Electronics Upgrades = 3
Weapon Upgrades = 3

; Navigation
Navigation = 3
Evasive Maneuvering = 1
Warp Drive Operation = 2
Afterburner = 3
High Speed Maneuvering = 1
Acceleration Control = 1

; Targeting
Target Management = 3
Long Range Targeting = 2
Signature Analysis = 2

; Electronic Warfare
Electronic Warfare = 1
Propulsion Jamming = 1

; Scanning
Astrometrics = 3
Astrometric Acquisition = 1
Astrometric Rangefinding = 1
Archaeology = 1
Hacking = 1

; Science
Science = 4
Cybernetics = 1
Infomorph Psychology = 1

; Trade
Trade = 3
Marketing = 1
Broker Relations = 1

; Social
Leadership = 1

; Salvaging
Salvaging = 3
