[character]
name = Cozzynk
last_updated = 2026-06-29

[skills]
; Spaceship Command
Spaceship Command = 5
Gallente Frigate = 3
Gallente Destroyer = 3
Gallente Cruiser = 3
Gallente Battlecruiser = 1
Gallente Hauler = 3
Gallente Drone Specialization = 1
Caldari Frigate = 3
Caldari Destroyer = 3
Caldari Cruiser = 3
Caldari Hauler = 5
ORE Hauler = 3
Mining Frigate = 3
Mining Destroyer = 1
Mining Barge = 5
Exhumers = 3
Industrial Command Ships = 2
Industrial Reconfiguration = 1
Transport Ships = 1

; Mining
Mining = 5
Mining Upgrades = 4
Astrogeology = 5
Mining Foreman = 5
Mining Director = 1
Mining Drone Operation = 4
Mining Drone Specialization = 0
Deep Core Mining = 0
Gas Cloud Harvesting = 5
Survey = 3
Simple Ore Processing = 3
Ubiquitous Moon Ore Processing = 3
Reprocessing = 4
Reprocessing Efficiency = 5

; Industry
Industry = 5
Mass Production = 5
Advanced Mass Production = 1
Metallurgy = 4

; Drones
Drones = 5
Drone Avionics = 3
Advanced Drone Avionics = 1
Drone Interfacing = 2
Drone Navigation = 3
Light Drone Operation = 3
Medium Drone Operation = 1

; Gunnery
Gunnery = 4
Small Hybrid Turret = 3
Medium Hybrid Turret = 3
Controlled Bursts = 2
Motion Prediction = 3
Rapid Firing = 2
Sharpshooter = 3
Trajectory Analysis = 1
Surgical Strike = 2

; Missiles
Missile Launcher Operation = 3

; Defence
Shield Operation = 3
Shield Management = 2
Shield Upgrades = 1
Tactical Shield Manipulation = 1
Hull Upgrades = 4
Mechanics = 3
Repair Systems = 3
Remote Armor Repair Systems = 2
Remote Hull Repair Systems = 2

; Engineering / fitting
CPU Management = 4
Power Grid Management = 4
Capacitor Management = 3
Capacitor Systems Operation = 3
Capacitor Emission Systems = 1
Energy Grid Upgrades = 2
Electronics Upgrades = 3
Weapon Upgrades = 3
Thermodynamics = 3

; Navigation
Navigation = 3
Evasive Maneuvering = 1
Warp Drive Operation = 4
Afterburner = 3
High Speed Maneuvering = 1
Acceleration Control = 1

; Targeting
Target Management = 3
Long Range Targeting = 2
Signature Analysis = 2

; Electronic Warfare
Electronic Warfare = 4
Propulsion Jamming = 1
Sensor Linking = 0
Cloaking = 3

; Scanning
Astrometrics = 3
Astrometric Acquisition = 3
Astrometric Rangefinding = 2
Archaeology = 1
Hacking = 1

; Science
Science = 4
Biology = 1
Cybernetics = 1
Infomorph Psychology = 2

; Trade
Trade = 4
Accounting = 3
Marketing = 1
Broker Relations = 1

; Social
Social = 1
Leadership = 1

; Salvaging
Salvaging = 3

; Planetary Industry
Command Center Upgrades = 4
Interplanetary Consolidation = 4
Planetology = 3
Advanced Planetology = 0
Remote Sensing = 3
